name       : libgxps
version    : 0.3.1
release    : 9
source     :
    - https://download.gnome.org/sources/libgxps/0.3/libgxps-0.3.1.tar.xz : 1a939fc8fcea9471b7eca46b1ac90cff89a30d26f65c7c9a375a4bf91223fa94
license    : LGPL-2.1-or-later
component  : programming.library
summary    : libgxps is a GObject based library for handling and rendering XPS documents
description: |
    libgxps is a GObject based library for handling and rendering XPS documents
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libarchive)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
