name       : libgxps
version    : 0.3.2
release    : 14
source     :
    - https://download.gnome.org/sources/libgxps/0.3/libgxps-0.3.2.tar.xz : 6d27867256a35ccf9b69253eb2a88a32baca3b97d5f4ef7f82e3667fa435251c
license    : LGPL-2.1-or-later
component  : programming.library
summary    : libgxps is a GObject based library for handling and rendering XPS documents
description: |
    libgxps is a GObject based library for handling and rendering XPS documents
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libarchive)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
