name       : libgxps
version    : 0.2.4
release    : 2
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libgxps/0.2/libgxps-0.2.4.tar.xz : e9d6aa02836d9d4823a51705d3e1dee6fc4bce11d72566024042cfaac56ec7a4
license    : LGPL-2.1
component  : programming
summary    : libgxps is a GObject based library for handling and rendering XPS documents
description: |
    libgxps is a GObject based library for handling and rendering XPS documents
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(gtk+-3.0)
    - libjpeg-turbo-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
