name       : libgxps
version    : 0.3.0
release    : 4
source     :
    - https://download.gnome.org/sources/libgxps/0.3/libgxps-0.3.0.tar.xz : 412b1343bd31fee41f7204c47514d34c563ae34dafa4cc710897366bd6cd0fae
license    : LGPL-2.1
component  : programming.library
summary    : libgxps is a GObject based library for handling and rendering XPS documents
description: |
    libgxps is a GObject based library for handling and rendering XPS documents
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libarchive)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - libjpeg-turbo-devel
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
