name       : libgxps
version    : 0.2.5
release    : 3
source     :
    - https://ftp.gnome.org/pub/gnome/sources/libgxps/0.2/libgxps-0.2.5.tar.xz : 3e7594c5c9b077171ec9ccd3ff2b4f4c4b29884d26d4f35e740c8887b40199a0
license    : LGPL-2.1
component  : programming
summary    : libgxps is a GObject based library for handling and rendering XPS documents
description: |
    libgxps is a GObject based library for handling and rendering XPS documents
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libarchive)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - libjpeg-turbo-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
